language: android
os: windows
android:
  components:
    # The BuildTools version used by your project
    - tools
    - build-tools-24.0.1
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19


before_install: chmod +x gradlew

notifications:
    email: false
