name: Build APK

on: [ push ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - run: echo 'TBA_KEY=\"${TBA_KEY}\"' > secrets.properties
      shell: bash
      env:
        TBA_KEY: ${{secrets.TBA_KEY}}
    - name: Build with Gradle
      run: ./gradlew clean assemble build
